<template>
  <div>

    <!-- Top bar with job icon/name (values loaded from src/data/research.js) -->
    <content-header :text="job.name" :icon="job.icon" :color="job.color" />


    <div class="content-container">

      <!-- XP bar and chem slot -->
      <div class="row mb-4 sticky">
        <div class="col-md-8 col-lg-9 col-xl-10">
          <experience-header :color="job.color" :jobId="jobId" />
        </div>
        <div class="mt-2 mt-md-0 col-md-4 col-lg-3 col-xl-2">
          <potion-header :jobId="jobId" />
        </div>
      </div>

      <!-- Tutorial box -->
      <job-info
        infoId="research"
        :icon="require('@/assets/art/jobinfo/research.png')"
        title="Magni Bronzebeard the Research Director says..."
        :options="[
          {name: 'Back'},
          {name: 'Research?', icon: require('@/assets/art/research/researchIcon.png'), iconClass:'mx--0'},
		      {name: 'Development?', icon: require('@/assets/art/research/protolathe.png'), iconClass:'mx--0'},
		      {name: 'TOOLs?', icon: require('@/assets/art/research/tools/toolGraytiding.png'), iconClass:'mx--0'},
          {name: 'Destructive Analyzer?', icon: require('@/assets/art/research/destructive_analyzer.gif'), iconClass:'mx--0'},
          {name: 'Points Bank?', icon: require('@/assets/art/research/points_bank.gif'), iconClass:'mx--0'},
        ]"
      >
        <template slot="Back">
          <span>
            Who let you in here? You're not a scientist. Oh, well... I suppose as long as you bring us 
            <img
              :src="require('@/assets/art/mining/SheetDiamond.png')"
            />
            <b>Precious Ores,</b> I'll let you use our Research and Development facilities.
          </span>
        </template>
        <template slot="Research?">
          <span>Here at R&D, we strive to create new technologies that have never been seen before.</span>
          <span>The 
            <img
              :src="require('@/assets/art/research/destructive_analyzer.gif')"
            />
            <b>Destructive Analyzer</b> basically does all the research work for us, so people usually come here to do development.</span>
		      <span>That said, there are some research projects we've been stuck on. If you can bring us some stuff to research by feeding it into the Destructive Analyzer, we can unlock new RECIPEs here and in other departments.</span>
        </template>
        <template slot="Development?">
          <span>Aside from 
            <img
              :src="require('@/assets/art/research/tools/toolGraytiding.png')"
            />
            <b>TOOLs,</b> developing stuff here usually requires something with unique functionality to make it out of, as well as some sweet, sweet ore.</span>
          <span>For example, night vision goggles might require some science goggles and uranium. Radioactivity makes things more scientific, and night vision itself is really scientific, so it only makes sense.</span>
        </template>
        <template slot="TOOLs?">
          <span>I'm sure you've heard of 
            <img
               class="mx--2" :src="require('@/assets/art/chemistry/faunaPerfume.png')" 
            />
            <b>CHEMs</b> from chemistry, right? Those are great and all, but our TOOLs can also give you cool temporary job upgrades without getting you addicted to meth.</span>
          <span>To use a TOOL, craft it and then equip it either from your inventory or with the BOOST slot at the top right of every job screen, just like you would with a CHEM.</span>
          <span>Just remember that operating machinery while under the influence is not advised. You can't use a TOOL and a CHEM at the same time, so it's up to you to decide which is best for the job.</span>
        </template>
        <template slot="Destructive Analyzer?">
          <span>Our method to get research points is to feed the computer stuff that it can learn from. That stuff can be almost anything, because science is about experimenting.</span>
          <span>The 
            <img
              :src="require('@/assets/art/research/destructive_analyzer.gif')"
            />
            <b>Destructive Analyzer</b> is like the mouth of the computer, so to speak. It asks for things to eat, and you feed them to it. In return, you get research points.</span>
          <span>If you can't get what the Destructive Analyzer is asking for, you can recalibrate it with the Reroll button, but doing so will cost you some experience.</span>
          <span>Research points are used to unlock RECIPEs, which you can see a list of below. RECIPEs are what will unlock those tasks that say they NEED RESEARCH, so you'll want to research them all!</span>
        </template>
        <template slot="Points Bank?">
          <span>Research data generated by the Destructive Analyzer is given to you in the form of 
            <img
              :src="require('@/assets/art/research/researchIcon.png')"
            />
            <b>Research Points.</b> Since you can't actually hold raw data with your hands, we store Research Points in the Points Bank server.</span>
          <span>The Points Bank can only hold so much data, though. If a RECIPE is asking for more points than you can store, you'll have to ask <img class="mx--0" :src="require('@/assets/art/sidebar/cargo.png')" />
            <b>Cargo</b> to upgrade our server.</span>
          <span>As you level up in R&D, the Destructive Analyzer will ask for harder-to-get things, but in return you'll get a lot more Research Points. Make sure to upgrade the Points Bank so that those points don't go to waste!</span>
        </template>
      </job-info>

      <!-- Research bank bar -->
      <div class="row mb-2">
        <div class="col-md-8 col-lg-9 col-xl-12">
          <research-bank :color="job.color" :jobId="jobId" />
        </div>
      </div>

      <!-- Bounty Box -->
      <div class="content-block d-flex flex-column align-items-center">
        <h5>
          <img
            :src="require('@/assets/art/research/destructive_analyzer.gif')"
          />
          <b> Destructive Analyzer </b>
          <img
            :src="require('@/assets/art/research/destructive_analyzer.gif')"
          />
        </h5>

        <div class="enemies w-100 mt-2">
          <research-bounty
          />
        </div>

      </div>

      <!-- Actions (generated from actions defined in src/data/research.js) -->

      <div
        class="tier row"
        v-for="(typedEntry, tier) in Object.entries(viewableTypedActionEntries)"
        :key="tier"
      >
        <div class="col-12">
          <span class="type-text text-uppercase">{{typedEntry[0]}}</span>
        </div>
        <div
          class="col-12 col-sm-6 col-lg-4 col-xl-3 col-xxl-2"
          v-for="[actionId, action] in typedEntry[1]"
          :key="actionId"
        >
          <generic-action
            :jobId="jobId"
            :actionName="'DEVELOP'"
            :action="action"
            :actionId="actionId"
          />
        </div>
      </div>

      <!-- Shop sections -->
      <div class="row">
        <div class="col-12">
          <shop-section v-for="(section, index) in sections" :key="index" :section="section" />
        </div>
      </div>

    </div>
  </div>
</template>

<script>
import { findLastIndex } from "lodash";
import { JOB } from "@/data/research";
import ContentAbstract from "@/components/Content/ContentAbstract";
import ExperienceHeader from "@/components/Content/ExperienceHeader";
import ResearchBank from "@/components/Content/ResearchBank";
import PotionHeader from "@/components/Content/PotionHeader";
import GenericAction from "@/components/Content/GenericAction";
import { mapState } from "vuex";
import ShopSection from "@/components/Content/Shop/ShopSection";
import { SECTIONS } from "@/data/recipesShop";//Dictates which file to load shop sections from
import ResearchBounty from "@/components/Content/ResearchBounty";
export default {
  extends: ContentAbstract,
  components: { GenericAction, ExperienceHeader, ResearchBank, PotionHeader, ShopSection, ResearchBounty },
  computed: {
    jobId() {
      return "research";
    },
    job() {
      return JOB;
    },
    viewableActions() {
      return this.$store.getters[this.jobId + "/filteredActionEntries"];
    },
    sections() {//Enables shop sections to load properly
      return SECTIONS;
    },
    rndPoints() {
      return this.$store.getters["research/rndPoints"];
    },
    viewableTypedActionEntries() {
      let entries = this.$store.getters[this.jobId + "/filteredActionEntries"];

      let toReturn = {}; // type: [entries]
      for (let entry of entries) {
        let type = entry[1].type;
        if (!toReturn[type]) toReturn[type] = [entry];
        else toReturn[type].push(entry);
      }

      return toReturn;
    },
  }
};
</script>

<style scoped>
.type-text {
  font-size: 20;
  font-weight: bold;
  color: rgba(245, 245, 245, 0.555);
}
img {
  width: 32px;
}
</style>
